"""
Demonstration of Style Guide Agent in action
Shows before/after transformations using real game content patterns.
"""

from style_guide_rules import TONE_GUIDELINES, VOCABULARY_GUIDELINES, FORMAT_GUIDELINES, GDD_REFERENCES

# Example content that would be generated by NPC Dialogue Agent
generated_content_examples = [
    {
        "name": "Tone Violation Example",
        "before": "The goose loudly honked at Hazel and she jumped in surprise! 'Oh my goodness - you startled me!' she exclaimed with enthusiasm.",
        "after": "The goose honked near Hazel by the bakery. She looked up, recognized the goose, and gave a small nod in acknowledgment."
    },
    {
        "name": "Vocabulary/Lore Inaccuracy Example", 
        "before": "The goose picked up an old toy from the mailbox and dropped it where the resident would find it - she was so surprised!",
        "after": "The goose retrieved a personal letter from Hazel's mailbox stand. A resident recognized it as a sentimental connection and looked thoughtful."
    },
    {
        "name": "Formatting/Length Issue Example",
        "before": "Wow! The goose grabbed a bundle of old letters from the counter, dropped them right where the resident would find them - everything was just perfect.",
        "after": "The goose retrieved an old letter from the mailbox stand. A resident recognized it as a personal memento and looked up in recognition."
    }
]

def demonstrate_style_guide_system():
    print("=== Gachō Badi Style Guide Agent Demonstration ===\n")
    
    print("GDD References:")
    for key, value in GDD_REFERENCES.items():
        print(f"  {key}: {value}")
    print()
    
    print("Style Guide Rules:")
    print("Tone Guidelines:")
    for key, value in TONE_GUIDELINES.items():
        print(f"  {key}: {value}")
    print()
    
    print("Vocabulary Guidelines:")  
    for key, value in VOCABULARY_GUIDELINES.items():
        print(f"  {key}: {value}")
    print()
    
    print("Formatting Guidelines:")
    for key, value in FORMAT_GUIDELINES.items():
        print(f"  {key}: {value}")
    print()
    
    print("Before/After Transformations:")
    for example in generated_content_examples:
        print(f"--- {example['name']} ---")
        print(f"Before: {example['before']}")
        print(f"After:  {example['after']}")
        print()

if __name__ == "__main__":
    demonstrate_style_guide_system()